@startuml
'https://plantuml.com/sequence-diagram
hide circle
skinparam classAttributeIconSize 0

class TimetableCommand {
    <u>+ COMMAND_WORD: String
    <u>+ COMMAND_USAGE: String
    <u>+ COMMAND_DESCRIPTION: String
    <u>- CONFLICTING_ERROR_MESSAGE: String
    <u>- EMPTY_TIMETABLE_ERROR_MESSAGE: String
    <u>- EXTRA_PARAMETERS_ERROR_MESSAGE: String
    <u>- FANCY_KEY: String
    <u>- MISSING_BACKSLASH_ERROR_MESSAGE: String
    <u>- SIMPLE_KEY: String
    - showFancy: boolean
    - showSimple: boolean

    - addToLessonsList(int, List<Pair<Module, RawLesson>>, SelectedModule)
    - addValidLesson(List<Pair<Module, RawLesson, Module, List<RawLesson>)
}
@enduml